import styles from "./pages.module.css";
import Card from "../card/Card";
import { useLocation } from "react-router-dom";

const switchRender = (path) => {
  switch (path) {
    case "":
      return [
        {
          id: 1,
          title: "Gold Rings",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 2,
          title: "Heart Necklaces",
          rate: 5,
          price: 7000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 3,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 5000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 4,
          title: "Silver watch",
          rate: 5,
          price: 1000,
          img: "assets/products/Silver watch.png",
        },
        {
          id: 5,
          title: "Gold Braceletes",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 6,
          title: "Gold Rings",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 7,
          title: "Gold Rings",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 8,
          title: "Gucci watch",
          rate: 5,
          price: 7000,
          img: "assets/products/Gucci watch.png",
        },
        {
          id: 9,
          title: "Gold Rings",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 10,
          title: "Gold Rings",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 11,
          title: "Silver Braceletes",
          rate: 5,
          price: 7000,
          img: "assets/products/Silver Braceletes.png",
        },
        {
          id: 12,
          title: "Gold watch",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold watch.png",
        },
        {
          id: 13,
          title: "Silver Rings",
          rate: 5,
          price: 1000,
          img: "assets/products/Silver Rings.png",
        },
        {
          id: 14,
          title: "Silver Rings",
          rate: 5,
          price: 7000,
          img: "assets/products/Silver Rings.png",
        },
        {
          id: 15,
          title: "Silver Braceletes",
          rate: 5,
          price: 5000,
          img: "assets/products/Silver Braceletes.png",
        },
      ];
    case "rings":
      return [
        {
          id: 1,
          title: "Gold Rings",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 2,
          title: "Gold Rings",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 3,
          title: "Gold Rings",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 4,
          title: "Gold Rings",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 5,
          title: "Gold Rings",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 6,
          title: "Gold Rings",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 7,
          title: "Gold Rings",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 8,
          title: "Silver Rings",
          rate: 5,
          price: 7000,
          img: "assets/products/Silver Rings.png",
        },
        {
          id: 9,
          title: "Silver Rings",
          rate: 5,
          price: 5000,
          img: "assets/products/Silver Rings.png",
        },
        {
          id: 10,
          title: "Silver Rings",
          rate: 5,
          price: 1000,
          img: "assets/products/Silver Rings.png",
        },
        {
          id: 11,
          title: "Gold Rings",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 12,
          title: "Gold Rings",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold Rings.png",
        },
        {
          id: 13,
          title: "Silver Rings",
          rate: 5,
          price: 1000,
          img: "assets/products/Silver Rings.png",
        },
        {
          id: 14,
          title: "Gold Rings",
          rate: 5,
          price: 7000,
          img: "assets/products/Silver Rings.png",
        },
        {
          id: 15,
          title: "Silver Rings",
          rate: 5,
          price: 5000,
          img: "assets/products/Silver Rings.png",
        },
      ];
    case "necklaces":
      return [
        {
          id: 1,
          title: "Heart Necklaces",
          rate: 5,
          price: 1000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 2,
          title: "Heart Necklaces",
          rate: 5,
          price: 7000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 3,
          title: "Heart Necklaces",
          rate: 5,
          price: 5000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 4,
          title: "Heart Necklaces",
          rate: 5,
          price: 1000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 5,
          title: "Heart Necklaces",
          rate: 5,
          price: 7000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 6,
          title: "Heart Necklaces",
          rate: 5,
          price: 5000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 7,
          title: "Heart Necklaces",
          rate: 5,
          price: 1000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 8,
          title: "Heart Necklaces",
          rate: 5,
          price: 7000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 9,
          title: "Heart Necklaces",
          rate: 5,
          price: 5000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 10,
          title: "Heart Necklaces",
          rate: 5,
          price: 1000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 11,
          title: "Heart Necklaces",
          rate: 5,
          price: 7000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 12,
          title: "Heart Necklaces",
          rate: 5,
          price: 5000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 13,
          title: "Heart Necklaces",
          rate: 5,
          price: 1000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 14,
          title: "Heart Necklaces",
          rate: 5,
          price: 7000,
          img: "assets/products/Heart Necklaces.png",
        },
        {
          id: 15,
          title: "Heart Necklaces",
          rate: 5,
          price: 5000,
          img: "assets/products/Heart Necklaces.png",
        },
      ];
    case "watches":
      return [
        {
          id: 1,
          title: "Silver watch",
          rate: 5,
          price: 1000,
          img: "assets/products/Silver watch.png",
        },
        {
          id: 2,
          title: "Gucci watch",
          rate: 5,
          price: 7000,
          img: "assets/products/Gucci watch.png",
        },
        {
          id: 3,
          title: "Silver watch",
          rate: 5,
          price: 5000,
          img: "assets/products/Silver watch.png",
        },
        {
          id: 4,
          title: "Gucci watch",
          rate: 5,
          price: 1000,
          img: "assets/products/Gucci watch.png",
        },
        {
          id: 5,
          title: "Silver watch",
          rate: 5,
          price: 7000,
          img: "assets/products/Silver watch.png",
        },
        {
          id: 6,
          title: "Gucci watch",
          rate: 5,
          price: 5000,
          img: "assets/products/Gucci watch.png",
        },
        {
          id: 7,
          title: "Silver watch",
          rate: 5,
          price: 1000,
          img: "assets/products/Silver watch.png",
        },
        {
          id: 8,
          title: "Gucci watch",
          rate: 5,
          price: 7000,
          img: "assets/products/Gucci watch.png",
        },
        {
          id: 9,
          title: "Silver watch",
          rate: 5,
          price: 5000,
          img: "assets/products/Silver watch.png",
        },
        {
          id: 10,
          title: "Gucci watch",
          rate: 5,
          price: 1000,
          img: "assets/products/Gucci watch.png",
        },
        {
          id: 11,
          title: "Silver watch",
          rate: 5,
          price: 7000,
          img: "assets/products/Silver watch.png",
        },
        {
          id: 12,
          title: "Gucci watch",
          rate: 5,
          price: 5000,
          img: "assets/products/Gucci watch.png",
        },
        {
          id: 13,
          title: "Silver watch",
          rate: 5,
          price: 1000,
          img: "assets/products/Silver watch.png",
        },
        {
          id: 14,
          title: "Gucci watch",
          rate: 5,
          price: 7000,
          img: "assets/products/Gucci watch.png",
        },
        {
          id: 15,
          title: "Silver watch",
          rate: 5,
          price: 5000,
          img: "assets/products/Silver watch.png",
        },
      ];
    case "earrings":
      return [
        {
          id: 1,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 1000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 2,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 7000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 3,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 5000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 4,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 1000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 5,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 7000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 6,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 5000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 7,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 1000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 8,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 7000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 9,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 5000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 10,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 1000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 11,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 7000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 12,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 5000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 13,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 1000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 14,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 7000,
          img: "assets/products/Small Hoop Earrings.png",
        },
        {
          id: 15,
          title: "Small Hoop Earrings",
          rate: 5,
          price: 5000,
          img: "assets/products/Small Hoop Earrings.png",
        },
      ];
    case "braceletes":
      return [
        {
          id: 1,
          title: "Gold Braceletes",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 2,
          title: "Gold Braceletes",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 3,
          title: "Gold Braceletes",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 4,
          title: "Gold Braceletes",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 5,
          title: "Gold Braceletes",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 6,
          title: "Gold Braceletes",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 7,
          title: "Gold Braceletes",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 8,
          title: "Gold Braceletes",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 9,
          title: "Gold Braceletes",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 10,
          title: "Gold Braceletes",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 11,
          title: "Silver Braceletes",
          rate: 5,
          price: 7000,
          img: "assets/products/Silver Braceletes.png",
        },
        {
          id: 12,
          title: "Gold Braceletes",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 13,
          title: "Gold Braceletes",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 14,
          title: "Gold Braceletes",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold Braceletes.png",
        },
        {
          id: 15,
          title: "Silver Braceletes",
          rate: 5,
          price: 5000,
          img: "assets/products/Silver Braceletes.png",
        },
      ];
    case "anklet":
      return [
        {
          id: 1,
          title: "Silver Anklet",
          rate: 5,
          price: 1000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 2,
          title: "Silver Anklet",
          rate: 5,
          price: 7000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 3,
          title: "Silver Anklet",
          rate: 5,
          price: 5000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 4,
          title: "Silver Anklet",
          rate: 5,
          price: 1000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 5,
          title: "Silver Anklet",
          rate: 5,
          price: 7000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 6,
          title: "Silver Anklet",
          rate: 5,
          price: 5000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 7,
          title: "Silver Anklet",
          rate: 5,
          price: 1000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 8,
          title: "Silver Anklet",
          rate: 5,
          price: 7000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 9,
          title: "Silver Anklet",
          rate: 5,
          price: 5000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 10,
          title: "Silver Anklet",
          rate: 5,
          price: 1000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 11,
          title: "Silver Anklet",
          rate: 5,
          price: 7000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 12,
          title: "Silver Anklet",
          rate: 5,
          price: 5000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 13,
          title: "Silver Anklet",
          rate: 5,
          price: 1000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 14,
          title: "Silver Anklet",
          rate: 5,
          price: 7000,
          img: "assets/products/Silver Anklet.png",
        },
        {
          id: 15,
          title: "Silver Anklet",
          rate: 5,
          price: 5000,
          img: "assets/products/Silver Anklet.png",
        },
      ];
    case "noseraings":
      return [
        {
          id: 1,
          title: "Gold nose raings",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 2,
          title: "Gold nose raings",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 3,
          title: "Gold nose raings",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 4,
          title: "Gold nose raings",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 5,
          title: "Gold nose raings",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 6,
          title: "Gold nose raings",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 7,
          title: "Gold nose raings",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 8,
          title: "Gold nose raings",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 9,
          title: "Gold nose raings",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 10,
          title: "Gold nose raings",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 11,
          title: "Gold nose raings",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 12,
          title: "Gold nose raings",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 13,
          title: "Gold nose raings",
          rate: 5,
          price: 1000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 14,
          title: "Gold nose raings",
          rate: 5,
          price: 7000,
          img: "assets/products/Gold nose raings.png",
        },
        {
          id: 15,
          title: "Gold nose raings",
          rate: 5,
          price: 5000,
          img: "assets/products/Gold nose raings.png",
        },
      ];
  }
};

export default function PageContent() {
  const pathName = useLocation().pathname.slice(1);

  return (
    <section className={styles.page}>
      <div className="row gap-5 justify-content-center">
        {switchRender(pathName).map((card) => {
          return <Card key={card.id} data={card} />;
        })}
      </div>
    </section>
  );
}
